### ISSUE TITLE
issues with `npm link`ing paratii-lib

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#276]
On this commit (but already way before) d5c7634d594b74d6a81db1366c459e932ddb60cf, `npm link paratii-lib` will break the webpack build with the  error below.

The error was introduced by importing `paratii-lib` in `embed.js` and `oembed.js`

I resolved this by adding the missing modules to `paratii-lib`. But the issue is at the portal, and should be resolved there.

```
[nodemon] starting `node src/server/index.js src/server/index.js`
/media/data/projects/paratii/paratii-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "babel-plugin-webpack-alias" specified in "base" at 0, attempted to resolve relative to "/media/data/projects/paratii/paratii-lib/lib"
    at /media/data/projects/paratii/paratii-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/media/data/projects/paratii/paratii-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/media/data/projects/paratii/paratii-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/media/data/projects/paratii/paratii-portal/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/media/data/projects/paratii/paratii-portal/node_modules/babel-register/lib/node.js:103:45)
    at loader (/media/data/projects/paratii/paratii-portal/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/media/data/projects/paratii/paratii-portal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/media/data/projects/paratii/paratii-portal/src/server/routes/embed.js:4:1)
    at Module._compile (module.js:635:30)
    at loader (/media/data/projects/paratii/paratii-portal/node_modules/babel-register/lib/node.js:144:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jellegerbrandy** [comment]
This was all my fault
