### ISSUE TITLE
erorr on build

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#39]
I did a fresh clone of the repo, ran `npm install`.

Now, `npm run dev` gives me the following error:

```
[0] ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/styles/app.scss
[0] Module build failed: Error: ENOENT: no such file or directory, scandir '/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/vendor'
[0]     at Object.fs.readdirSync (fs.js:904:18)
[0]     at Object.getInstalledBinaries (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/extensions.js:128:13)
[0]     at foundBinariesList (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/errors.js:20:15)
[0]     at foundBinaries (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/errors.js:15:5)
[0]     at Object.module.exports.missingBinary (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/errors.js:45:5)
[0]     at module.exports (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/binding.js:15:30)
[0]     at Object.<anonymous> (/media/data/projects/paratii/paratii-portal2/node_modules/node-sass/lib/index.js:14:35)
[0]     at Module._compile (module.js:635:30)
[0]     at Object.Module._extensions..js (module.js:646:10)
[0]     at Module.load (module.js:554:32)
[0]     at tryModuleLoad (module.js:497:12)
[0]     at Function.Module._load (module.js:489:3)
[0]     at Module.require (module.js:579:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (/media/data/projects/paratii/paratii-portal2/node_modules/sass-loader/lib/loader.js:3:14)
[0]     at Module._compile (module.js:635:30)
[0]     at Object.Module._extensions..js (module.js:646:10)
[0]     at Module.load (module.js:554:32)
[0]     at tryModuleLoad (module.js:497:12)
[0]     at Function.Module._load (module.js:489:3)
[0]     at Module.require (module.js:579:17)
[0]     at require (internal/module.js:11:18)
[0]     at loadLoader (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/loadLoader.js:13:17)
[0]     at iteratePitchingLoaders (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
[0]     at iteratePitchingLoaders (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
[0]     at /media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:173:18
[0]     at loadLoader (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/loadLoader.js:36:3)
[0]     at iteratePitchingLoaders (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
[0]     at iteratePitchingLoaders (/media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
[0]     at /media/data/projects/paratii/paratii-portal2/node_modules/loader-runner/lib/LoaderRunner.js:173:18
[0]  @ ./src/styles/app.scss 4:14-168 18:2-22:4 19:20-174
[0]  @ ./src/scripts/index.js
[0]  @ multi react-hot-loader/patch ./src/scripts/index.js webpack-hot-middleware/client?quiet=true
```

**Comment by bent0b0x** [comment]
Already mentioned on gitter, but `npm rebuild node-sass` _should_ fix this

**Comment by jellegerbrandy** [comment]
worked. Added a line in the readme mentioning this.
